export const MESSAGE_OPENER_CATEGORY_IDS = [
  "shared_interest",
  "same_city",
  "creator_fan",
  "compliment",
  "flirty",
  "funny",
  "would_you_rather",
  "hot_take",
  "quick_game",
  "date_energy",
  "straight_up",
  "curious",
  "playful",
  "spicy",
  "confident",
] as const;

export type MessageOpenerCategoryId = (typeof MESSAGE_OPENER_CATEGORY_IDS)[number];

export type MessageOpenerCategory = {
  value: MessageOpenerCategoryId;
  label: string;
  openers: readonly string[];
  seekerOnly?: boolean;
};

const SEEKER_OPENER_ORDER: readonly MessageOpenerCategoryId[] = [
  "flirty",
  "compliment",
  "funny",
  "playful",
  "spicy",
  "would_you_rather",
  "quick_game",
  "hot_take",
  "date_energy",
  "curious",
  "confident",
  "straight_up",
  "shared_interest",
  "same_city",
];

export const MESSAGE_OPENER_CATEGORIES: readonly MessageOpenerCategory[] = [
  {
    value: "shared_interest",
    label: "Shared interest",
    openers: [
      "Okay, we clearly have the same taste. What got you into it?",
      "I saw we’re into the same thing and had to investigate further.",
      "Finally, someone who gets it. What’s your favourite part?",
      "Our shared interest just gave me the perfect excuse to say hi.",
      "You like that too? Be honest, how deep does the obsession go?",
      "I spotted our common interest and thought, yep, my kind of person.",
      "We already agree on one important thing. That feels promising.",
      "Quick one: what’s your hottest take about our shared interest?",
      "I need your expert opinion on something we both clearly enjoy.",
      "Our algorithms may have actually cooked with this match.",
      "Same interest, similar vibe… should we compare notes?",
      "You had me at the part of your profile we both geek out about.",
      "I feel like we could talk about this for an irresponsible amount of time.",
      "What’s the one recommendation you’d give a fellow fan?",
      "Not to be dramatic, but our shared taste is already a green flag.",
      "I came for the shared interest; I stayed because your vibe looks solid.",
      "Rate your obsession from casual fan to full documentary narrator.",
      "We have that in common, so I trust your judgement already.",
      "What’s something about it only a real fan would understand?",
      "Tell me your favourite and I’ll tell you whether we can be friends.",
      "I’m collecting good opinions on this topic. Please contribute yours.",
      "Our mutual interest deserves at least one proper conversation.",
      "What was the moment you knew this was your thing?",
      "You seem like someone with elite recommendations. Prove me right.",
      "I noticed the common ground. Shall we build on it?",
      "I have questions, opinions, and possibly a controversial ranking.",
      "This is me respectfully entering your DMs through our shared interest.",
      "We like the same thing, but do we have the same favourite?",
      "Your profile says you know the vibe. What should I try next?",
      "Shared interest unlocked. Now tell me the story behind yours.",
      "I was going to say hi normally, then I saw we both love this.",
      "Let’s skip small talk: give me your top three.",
      "What’s your most unpopular opinion about the thing we both like?",
      "You passed the taste check. I had to say hello.",
      "I think we just found our first conversation rabbit hole.",
      "So who introduced you to it, or did you discover it yourself?",
      "Our common interest is doing excellent wingman work right now.",
      "I need to know whether your taste is as good as your profile suggests.",
      "This shared interest could either unite us or start a playful debate.",
      "You look like you’d have a very specific favourite. Am I right?",
      "Okay fellow enthusiast, what’s one thing everyone gets wrong about it?",
      "We already have conversation material. The universe made this easy.",
      "Your take on this might decide whether I’m impressed or obsessed.",
      "I saw the shared interest and immediately wanted the full backstory.",
      "Do we enjoy this the same way, or are we about to debate?",
      "I’m curious: beginner phase, serious hobby, or full lifestyle?",
      "You’ve got good taste. Yes, I’m including myself in that compliment.",
      "What’s the best memory you have connected to our shared interest?",
      "I feel like there’s a very good conversation hiding here.",
      "Since we both like it, you’re now responsible for one recommendation.",
      "I’ve found my people. Well, potentially my person.",
      "Your profile just made our shared interest look even more interesting.",
      "Should we exchange favourites or jump straight into hot takes?",
      "I’m here to confirm whether your opinions match your excellent vibe.",
      "Common ground this early? We might be overachieving.",
      "What’s the one question you wish people asked you about it?",
      "I saw we share this interest and my curiosity clocked in immediately.",
      "Let’s settle something important: what belongs at number one?",
      "There’s no way I was scrolling past a fellow fan without saying hi.",
      "We have the same interest. Now I need to know if the banter matches.",
    ],
  },
  {
    value: "same_city",
    label: "Same city",
    openers: [
      "Same city? Suddenly the internet feels very small.",
      "We’re in the same city, so what spot never disappoints you?",
      "Local question: where do you go when you need immaculate vibes?",
      "Same city and you still managed to feel like a rare find.",
      "What’s your favourite hidden gem around here?",
      "Since we’re local, I need your most honest food recommendation.",
      "Be honest: are you outside often or proudly indoors?",
      "Same city means we can argue about the best neighbourhood properly.",
      "What place here deserves more hype than it gets?",
      "Our locations match. Let’s see whether the energy does too.",
      "Small world. What part of the city feels most like you?",
      "I’m looking for someone with better local recommendations than Google.",
      "Same city? Name one place you’d happily visit twice in one week.",
      "What’s your ideal low-key day around here?",
      "You seem like you know where the good vibes are hiding.",
      "Local people only: what’s one place that’s completely overrated?",
      "We’re nearby, so distance can’t take the blame if we never talk.",
      "What’s your go-to plan when you want to escape the city without leaving it?",
      "Same city, same app, suspiciously good timing.",
      "Which local spot matches your personality best?",
      "Tell me where the best late-night food is and I’ll trust you forever.",
      "I noticed we’re local and decided to mind your business respectfully.",
      "What’s the most fun thing you’ve done here recently?",
      "Same city unlocked. Now give me one elite recommendation.",
      "Are you more rooftop views, quiet cafés, or spontaneous linkups?",
      "Which part of town always has your money somehow?",
      "We might have crossed paths before. Should we make the next one intentional?",
      "What local place instantly improves your mood?",
      "Same city, but I’m guessing your version of it is more interesting.",
      "If you had one free evening here, where are you going?",
      "I need a city guide with personality. You look qualified.",
      "Where do you take someone when you want them to understand your vibe?",
      "What’s the city’s best-kept secret, in your opinion?",
      "Our city is big, but your profile still found me. Cute.",
      "Let’s test your local taste: best food, best music, best view?",
      "Are you team planned outing or ‘let’s just see where the night goes’?",
      "Same location is convenient. Good chemistry would be even better.",
      "Which local event can always convince you to leave the house?",
      "I’m taking recommendations from attractive locals only.",
      "What’s one thing you genuinely love about living here?",
      "Same city—should we compare favourite spots or unpopular opinions?",
      "You look like you know one quiet place nobody else has discovered.",
      "What’s your perfect Sunday in this city?",
      "If the city had a personality, would you two get along?",
      "I’m curious which side of the city gets the best version of you.",
      "What’s your ‘I need fresh air and good food’ location?",
      "We’re local enough for recommendations and far enough for mystery.",
      "Name the local meal you’d defend with your whole chest.",
      "Same city? Let me guess—you still haven’t visited half the cool places.",
      "What neighbourhood has the best energy after dark?",
      "I came to ask for a recommendation and possibly your attention.",
      "Which local spot would make a perfect first conversation?",
      "You get one chance to impress me with a city recommendation.",
      "What’s the most unserious thing about living here?",
      "Same city and matching vibes would be a dangerous combination.",
      "If we accidentally met outside, where would it most likely happen?",
      "What’s your favourite way to spend a soft-life afternoon here?",
      "Local compatibility test: food first, drinks first, or activity first?",
      "I’m convinced every city has main characters. You look suspicious.",
      "We already share a postcode area. Shall we try a conversation too?",
    ],
  },
  {
    value: "creator_fan",
    label: "Creator/Fan",
    openers: [
      "Your content made me stop scrolling, so I came to say hi properly.",
      "You make this look effortless. What part takes the most work?",
      "I found your content and now I understand why people stay.",
      "Your creative brain seems like a fun place. What inspires it lately?",
      "I came as a viewer, but your personality made me curious.",
      "That last post deserved more than a silent like.",
      "Your content has a very specific flavour. I rate it.",
      "What’s something you’ve always wanted to create but haven’t yet?",
      "You’re good at catching attention. Consider mine caught.",
      "I like how your content actually sounds like a real person made it.",
      "Your page has range. Which side of it feels most like you?",
      "I need the behind-the-scenes story on your favourite post.",
      "Your content passed the vibe check with unnecessary ease.",
      "Do your best ideas arrive peacefully or at 2 a.m. with chaos?",
      "You have the kind of page that makes people curious about the person.",
      "I’m officially a fan of the content and potentially the creator too.",
      "Which piece of your work are you secretly most proud of?",
      "Your consistency is impressive. Please tell me there’s a chaotic draft folder.",
      "I like the way you see things. It feels refreshingly yours.",
      "Your content made me laugh, pause, and then open your profile. Strong work.",
      "What’s one idea your audience loved that surprised you?",
      "You’ve built a whole vibe here. How did it start?",
      "I was going to compliment one post, but honestly the whole page is good.",
      "Your creativity looks expensive—in the best way.",
      "What do you enjoy creating even when nobody is watching?",
      "Your page feels like a conversation already, so I’m joining in.",
      "I respect anyone who can make originality look this natural.",
      "Which comment from a follower has stayed with you?",
      "Your content has personality. That’s rarer than it should be.",
      "I’m curious about the person behind all this good taste.",
      "You clearly know your audience, but what content do you make for yourself?",
      "That creative confidence? Very attractive, by the way.",
      "Your page feels like you actually enjoy what you do.",
      "I’m here to give your content its flowers while you can reply.",
      "What’s the most random thing that has inspired one of your posts?",
      "You make people want to pay attention. That’s a real skill.",
      "Your work has sauce. I don’t make the rules.",
      "How much of your content is planned and how much is beautiful chaos?",
      "I saw your page and thought, this person definitely has stories.",
      "Your creativity has main-character energy without trying too hard.",
      "What’s one thing people misunderstand about being a creator?",
      "The content is good, but your energy might be the real hook.",
      "I’m not usually in creators’ DMs, but your page made a strong case.",
      "You create the kind of stuff people send to the group chat.",
      "Which post best represents who you are off camera?",
      "I appreciate content that has both effort and personality. Yours does.",
      "You’ve got the rare ‘one more post’ kind of page.",
      "I started with one post and somehow completed a small research project.",
      "What’s your favourite part: the idea, the making, or the reaction?",
      "Your content feels confident. Were you always this comfortable sharing?",
      "Respectfully, your page is dangerously easy to keep scrolling.",
      "I like the mind behind the content. I’d love to hear more from it.",
      "Your audience gets the polished version. What’s the fun messy version like?",
      "This is your reminder that your work is genuinely landing.",
      "You make your niche look like the place to be.",
      "I’ve liked quietly long enough. Hello from the other side of the screen.",
      "Your content feels like good music—you notice when it stops.",
      "What would you create tomorrow if budget and fear both disappeared?",
      "I came to compliment the content, but your smile complicated the mission.",
      "Keep creating, but maybe keep a little time for this conversation too.",
    ],
  },
  {
    value: "compliment",
    label: "Compliment",
    openers: [
      "Your smile looks like it has excellent timing.",
      "You have the kind of face a camera remembers.",
      "Your style is doing exactly what it needs to do.",
      "You look like good news with great lighting.",
      "Your profile has such calm, attractive energy.",
      "You somehow look both soft and unforgettable.",
      "The confidence in your photos is genuinely beautiful.",
      "You have a very ‘worth getting to know’ kind of vibe.",
      "Your eyes look like they know a good story.",
      "You make effortless look suspiciously convincing.",
      "Your whole profile feels warm in a really lovely way.",
      "You have excellent taste, starting with how you present yourself.",
      "That smile could improve somebody’s entire week.",
      "You look like the person everyone secretly hopes shows up.",
      "Your energy comes through the screen. That’s rare.",
      "There’s something very magnetic about how you carry yourself.",
      "Your profile is equal parts beautiful and interesting.",
      "You look like kindness and mischief agreed to collaborate.",
      "That outfit deserves its own round of applause.",
      "You have a face that makes people forget their original point.",
      "Your vibe feels expensive, but not in a trying-too-hard way.",
      "You seem comfortable being yourself. It looks good on you.",
      "Your smile has genuine ‘come closer’ energy.",
      "You’re giving beauty, personality, and very little room to scroll past.",
      "The way you put yourself together is seriously attractive.",
      "You look like you make ordinary plans feel special.",
      "Your profile feels like a really good first impression.",
      "You have such a distinct look. Nobody could confuse your energy.",
      "Your confidence is easily your best accessory.",
      "You look like the main reason a room becomes more interesting.",
      "Your face card is clearly not observing office hours.",
      "You have that rare mix of cute and composed.",
      "Your photos feel alive. You can tell there’s personality behind them.",
      "Your style says you know exactly what works for you.",
      "You make looking good seem almost disrespectfully easy.",
      "There’s a softness in your expression that really stands out.",
      "You look like someone people feel lucky to know.",
      "The energy on your profile is genuinely refreshing.",
      "Your smile is doing some very convincing marketing for you.",
      "You have the kind of beauty that gets more interesting the longer you look.",
      "Your presence feels strong even through a screen.",
      "You look like you give elite hugs and honest advice.",
      "That photo is a masterclass in knowing your angles.",
      "You have a naturally elegant vibe. It’s lovely.",
      "Your profile made ‘just one more scroll’ impossible.",
      "You look like peace with a little bit of trouble mixed in.",
      "The smile, the style, the energy—you understood the assignment.",
      "You have one of those faces that feels instantly familiar.",
      "Your pictures have personality, not just good lighting.",
      "You look like someone who leaves a very good impression.",
      "Your whole vibe says soft life with standards.",
      "Your eyes are honestly doing most of the talking already.",
      "You’re photogenic, but I’m guessing you’re even better in motion.",
      "You have such an easy, attractive confidence.",
      "Your profile feels considered without feeling staged.",
      "You look like the compliment people are too shy to say out loud.",
      "That smile has no business being this persuasive.",
      "You’re very easy on the eyes and hard on the attention span.",
      "Your energy feels like a favourite song on the first listen.",
      "You’re genuinely stunning, but the vibe is what made me stop.",
    ],
  },
  {
    value: "flirty",
    label: "Flirty",
    openers: [
      "Are you always this distracting, or is today special?",
      "I had a smooth opener, then your face reset my brain.",
      "You look like exactly the kind of trouble I’d reply to quickly.",
      "I’m trying to play it cool, but your profile is not cooperating.",
      "So when were you planning to tell me you’re my type?",
      "You’re cute. I’m cute. This conversation has potential.",
      "I blame your smile for this message.",
      "You look like someone I could flirt with professionally.",
      "Should we pretend this was a chance meeting or admit I’m interested?",
      "I’m not saying you’re my type, but my type is feeling represented.",
      "Your profile just interrupted my peaceful scrolling.",
      "You look like you’d make eye contact and ruin my whole plan.",
      "I came to say hi before somebody less charming got here first.",
      "I feel like our banter could become a public safety concern.",
      "Are you good at conversation, or do you just look this convincing?",
      "You seem worth risking a slightly embarrassing first message for.",
      "I’m curious whether your personality is as attractive as your face.",
      "My screen time report is about to blame you personally.",
      "I was minding my business, then your profile became my business.",
      "You look like a reason to turn notifications on.",
      "Is it too early to say we’d look good laughing together?",
      "You have ‘reply immediately’ energy. Very inconvenient.",
      "Be honest—how many people forgot their opener on this profile?",
      "I’d ask if you come here often, but I’d rather ask when you’re free.",
      "Your smile is flirting first, so technically this is self-defence.",
      "You look like the plot twist my week could use.",
      "I’m usually sensible, but then again, you’re very attractive.",
      "I think your profile and my attention are officially exclusive.",
      "If your vibe is this good online, in person might be dangerous.",
      "You’ve got the kind of face that makes confidence arrive late.",
      "I’m here to test whether the chemistry matches the pictures.",
      "Can we skip the part where we pretend we’re not flirting?",
      "You look like someone I’d accidentally talk to until 2 a.m.",
      "I saw you and suddenly ‘hey’ felt wildly underdressed.",
      "There’s attractive, and then there’s whatever you’re doing here.",
      "You seem like a very good reason to lose track of time.",
      "I’m willing to share my best banter if you are.",
      "Your profile says ‘approach carefully.’ I chose confidently.",
      "I think we should investigate this mutual potential immediately.",
      "Do you always make strangers this curious?",
      "You look like a slow reply would hurt my feelings a little.",
      "I’m deciding between complimenting you and asking you out. Thoughts?",
      "Your face is cute, but your energy is doing the real damage.",
      "I have a feeling you’re even more attractive when you laugh.",
      "The algorithm put you here and I choose to believe in fate now.",
      "You’re giving ‘worth the double text,’ and that’s powerful.",
      "I’d like to know the person behind this unfairly attractive profile.",
      "I’m not flirting yet. This is just an extremely interested hello.",
      "Your profile feels like a dare to say something memorable.",
      "I can already tell you’d be a very distracting conversation.",
      "Are we both going to act shy, or should I keep being brave?",
      "You look like the kind of person a good playlist gets made for.",
      "I’m respectfully asking for a little of your attention.",
      "Your vibe is dangerously close to everything I like.",
      "I don’t chase, but I do send excellent first messages.",
      "You’ve got a smile that could talk me into plans.",
      "I came for the face card; I’m staying to check the personality.",
      "You seem like you’d flirt back with proper technique.",
      "Let’s find out whether we’re as interesting together as I suspect.",
      "Hi. I’m choosing honesty: I think you’re very, very attractive.",
    ],
  },
  {
    value: "funny",
    label: "Funny",
    openers: [
      "Important compatibility test: do you return borrowed chargers?",
      "Quick question before feelings develop: pineapple on pizza?",
      "You look like you have strong opinions about very unserious things.",
      "I’m conducting research on attractive people. Care to participate?",
      "My opener budget was small, so please accept this premium hello.",
      "Be honest: how many alarms do you set in the morning?",
      "You seem funny. Please don’t make me carry this conversation alone.",
      "I was told to follow my dreams, so unfortunately I’m in your DMs.",
      "Rate this entrance from one to ‘thank God they messaged.’",
      "If we vibe, I’ll delete the three worse openers I drafted.",
      "What’s your most defendable red flag? Mine is asking questions like this.",
      "I bring humour, snacks, and occasionally correct directions.",
      "Are you emotionally available or just extremely photogenic?",
      "I need a second opinion: is this chemistry or excellent Wi-Fi?",
      "If awkward first messages build character, I’m becoming powerful.",
      "You look like you’d laugh when you’re supposed to be serious.",
      "I promise I’m smoother after the loading screen.",
      "What’s your toxic trait? Mine is thinking I can cook without a recipe.",
      "I’d use a pickup line, but you deserve at least mid-level originality.",
      "We should talk before my courage remembers it has somewhere else to be.",
      "Choose wisely: deep conversation or ranking random snacks?",
      "I’m cute in person; this message is not my final form.",
      "You look like you’ve sent ‘I’m five minutes away’ from the shower.",
      "Breaking news: local person says hi to attractive stranger.",
      "What’s a completely useless skill you’re weirdly proud of?",
      "I almost sent ‘hey,’ but my ancestors asked me to add personality.",
      "Please reply quickly; I told my imaginary audience this would work.",
      "Do you cook, or are we both surviving on confidence?",
      "I have one joke and several good intentions. Interested?",
      "You seem like someone who reads menus before reaching the restaurant.",
      "If you ghost me, at least recommend a good series first.",
      "Our first argument can be about whether naps count as hobbies.",
      "What’s your most embarrassing autocorrect story? I need balance here.",
      "You look expensive. My personality is currently on promotion.",
      "I’m here with confidence I absolutely did not earn.",
      "Would you rather fight one goat-sized pigeon or ten pigeon-sized goats?",
      "I need to know if your humour is clever or just loud like mine.",
      "How do you feel about people who steal fries after saying they’re not hungry?",
      "I’ve reviewed your profile and found insufficient evidence of bad vibes.",
      "My lawyer advised me to say hello before making more assumptions.",
      "Are you a fast replier or should I start a small hobby?",
      "I’m not saying this is fate, but my data plan brought me here.",
      "You look like you know when to leave the group chat on mute.",
      "What’s the pettiest hill you’re willing to die on?",
      "I’d offer you a fun fact, but your profile is already distracting.",
      "This message has been approved by exactly zero responsible adults.",
      "If conversation were food, what are you bringing to the table?",
      "You have 30 seconds to name a better opener than this.",
      "I’m accepting applications for someone to laugh at my best jokes.",
      "Do you also open the fridge repeatedly hoping new food appears?",
      "I can’t promise perfection, but I can promise elite reaction memes.",
      "What’s your emergency karaoke song? This matters more than it should.",
      "I’m trying something new called ‘speaking to people I find attractive.’",
      "You look like you’d enable a very unnecessary late-night food order.",
      "Should we exchange life stories or start with our worst fashion era?",
      "I was going to play hard to get, but I got confused and came here.",
      "Tell me your funniest lie from childhood and I’ll judge respectfully.",
      "You seem normal, which is exactly what a funny person would pretend.",
      "My opening line is currently in traffic. Hi in the meantime.",
      "Let’s skip awkward silence and debate something completely pointless.",
    ],
  },
  {
    value: "would_you_rather",
    label: "Would you rather",
    seekerOnly: true,
    openers: [
      "Would you rather have unlimited flights or unlimited food delivery?",
      "Would you rather plan every date or be surprised every time?",
      "Would you rather give up music for a month or social media for a year?",
      "Would you rather always be ten minutes early or twenty minutes late?",
      "Would you rather date a great cook or a great dancer?",
      "Would you rather have a beach day or a rainy day indoors?",
      "Would you rather know everyone’s thoughts or never be misunderstood?",
      "Would you rather do karaoke together or take a dance class?",
      "Would you rather travel with no plan or schedule every stop?",
      "Would you rather have chemistry instantly or let it build slowly?",
      "Would you rather lose your phone for a week or your favourite shoes forever?",
      "Would you rather be the funniest person there or the most mysterious?",
      "Would you rather cook dinner together or hunt down the best street food?",
      "Would you rather receive flowers or a perfectly chosen playlist?",
      "Would you rather relive your best day or skip your worst one?",
      "Would you rather text all day or have one long late-night call?",
      "Would you rather have a private beach or a private cinema?",
      "Would you rather be famous for talent or quietly wealthy?",
      "Would you rather share dessert or order two and taste both?",
      "Would you rather always say exactly what you feel or keep some mystery?",
      "Would you rather meet someone through friends or by complete accident?",
      "Would you rather get dressed up or keep the date effortlessly casual?",
      "Would you rather have breakfast dates or midnight food runs?",
      "Would you rather be flirted with through words or eye contact?",
      "Would you rather revisit the past or preview one day in your future?",
      "Would you rather be stuck in traffic with me or lost on a road trip?",
      "Would you rather have perfect photos together or hilarious memories nobody filmed?",
      "Would you rather win every argument or never need to argue?",
      "Would you rather dance in public or sing loudly in the car?",
      "Would you rather choose the movie or control the snacks?",
      "Would you rather live somewhere exciting or somewhere peaceful?",
      "Would you rather be adored loudly or loved quietly but deeply?",
      "Would you rather have one unforgettable date or ten comfortably good ones?",
      "Would you rather date someone exactly like you or your total opposite?",
      "Would you rather get a thoughtful gift or an unexpected experience?",
      "Would you rather never use emojis again or only communicate with voice notes?",
      "Would you rather spend a weekend outside or under a blanket?",
      "Would you rather have a personal chef or a personal driver?",
      "Would you rather laugh through a bad date or escape after ten minutes?",
      "Would you rather know how we meet or how our story ends?",
      "Would you rather have a partner who hypes you publicly or protects your peace privately?",
      "Would you rather go to a loud party or host a tiny dinner?",
      "Would you rather receive a risky text or send one first?",
      "Would you rather have unlimited confidence or unlimited patience?",
      "Would you rather match outfits intentionally or accidentally?",
      "Would you rather fall for someone’s mind or their energy first?",
      "Would you rather explore a new city or return to a favourite place?",
      "Would you rather be called cute or irresistible?",
      "Would you rather have deep talks at 2 a.m. or silly chats all afternoon?",
      "Would you rather share your location or your dessert? Choose carefully.",
      "Would you rather be surprised with a trip or choose the destination together?",
      "Would you rather make the first move or be confidently pursued?",
      "Would you rather have a relationship full of adventure or full of calm?",
      "Would you rather see my camera roll or my search history?",
      "Would you rather cancel plans together or make spontaneous ones?",
      "Would you rather have perfect timing or undeniable chemistry?",
      "Would you rather flirt subtly all night or say exactly what you want?",
      "Would you rather tell me your biggest green flag or your funniest red one?",
      "Would you rather take a compatibility quiz or trust the vibe?",
      "Would you rather answer honestly or let me guess your choice?",
    ],
  },
  {
    value: "hot_take",
    label: "Hot take",
    seekerOnly: true,
    openers: [
      "Hot take: brunch is mostly about outfits. Agree or defend it?",
      "Unpopular opinion: voice notes are either intimate or a full podcast.",
      "Hot take: good banter matters more than matching hobbies.",
      "Unpopular opinion: first dates should never involve the cinema.",
      "Hot take: sharing food is more serious than sharing passwords.",
      "Unpopular opinion: slow replies are fine if the replies have substance.",
      "Hot take: attraction can grow, but bad conversation rarely recovers.",
      "Unpopular opinion: breakfast dates deserve more respect.",
      "Hot take: matching music taste is a legitimate compatibility test.",
      "Unpopular opinion: being funny is more attractive than being mysterious.",
      "Hot take: ‘I’m bad at texting’ is sometimes just honest branding.",
      "Unpopular opinion: the best dates have one plan and room for chaos.",
      "Hot take: dessert should arrive before anybody says they’re full.",
      "Unpopular opinion: flirting through memes absolutely counts.",
      "Hot take: being able to sit in silence is elite chemistry.",
      "Unpopular opinion: fancy restaurants are not automatically romantic.",
      "Hot take: everyone has one song that exposes their entire personality.",
      "Unpopular opinion: a good morning text can fix unreasonable amounts.",
      "Hot take: chemistry is obvious in the first ten minutes.",
      "Unpopular opinion: planned dates are more romantic than spontaneous ones.",
      "Hot take: the person who invites should choose the place.",
      "Unpopular opinion: stealing fries is an act of affection.",
      "Hot take: eye contact is louder than most compliments.",
      "Unpopular opinion: soft life is a mindset before it’s a budget.",
      "Hot take: a shared sense of humour can carry almost any conversation.",
      "Unpopular opinion: ‘wyd’ can work if the person is attractive enough.",
      "Hot take: a thoughtful playlist is more romantic than flowers.",
      "Unpopular opinion: everybody should have a signature meal they can cook.",
      "Hot take: first impressions matter, but second impressions reveal more.",
      "Unpopular opinion: replying quickly is attractive, not desperate.",
      "Hot take: being consistent is hotter than acting unavailable.",
      "Unpopular opinion: staying in can be a better date than going out.",
      "Hot take: people reveal themselves by how they handle small inconveniences.",
      "Unpopular opinion: the aux cord is a position of trust.",
      "Hot take: chemistry without peace gets old very quickly.",
      "Unpopular opinion: ‘we’ll see’ usually means absolutely not.",
      "Hot take: asking good questions is an underrated form of flirting.",
      "Unpopular opinion: every couple needs separate hobbies.",
      "Hot take: nicknames are only cute when they happen naturally.",
      "Unpopular opinion: a laugh can be more attractive than a smile.",
      "Hot take: the best compliments notice something beyond appearance.",
      "Unpopular opinion: one great photo beats twelve confusing ones.",
      "Hot take: you can tell a lot by someone’s food order.",
      "Unpopular opinion: long phone calls are making a comeback.",
      "Hot take: confidence without kindness is just noise.",
      "Unpopular opinion: the person with better taste should choose the movie.",
      "Hot take: a little healthy teasing improves the chemistry.",
      "Unpopular opinion: cancelling plans can be a love language sometimes.",
      "Hot take: everyone looks better when they’re talking about what they love.",
      "Unpopular opinion: attraction starts with curiosity, not appearance.",
      "Hot take: date ideas reveal more than profile bios.",
      "Unpopular opinion: people who say ‘no drama’ often bring the trailer.",
      "Hot take: the best conversations start with a risky honest question.",
      "Unpopular opinion: being predictable can feel safe in a good way.",
      "Hot take: compatibility matters more than having a perfect type.",
      "Unpopular opinion: a person’s laugh should be on their profile.",
      "Hot take: playful competition is basically flirting with rules.",
      "Unpopular opinion: the best part of a date is the unplanned conversation after.",
      "Hot take: real confidence includes knowing when to be soft.",
      "Your turn: give me a hot take you’d defend without notes.",
    ],
  },
  {
    value: "quick_game",
    label: "Quick game",
    seekerOnly: true,
    openers: [
      "Quick game: two truths and a lie. You first.",
      "Describe your dating style using only three emojis.",
      "Pick a number from one to five and I’ll ask the matching question.",
      "Give me three clues and I’ll guess your favourite hobby.",
      "One-word answers only: what’s your current mood?",
      "Name three things in your perfect weekend. No explanations yet.",
      "Guess my first impression of you and I’ll tell you how close you are.",
      "Choose one: truth, dare, or dangerously honest question?",
      "Tell me your top three snacks and I’ll profile you respectfully.",
      "Five-second challenge: name a song you never skip.",
      "Give me one green flag and one harmless red flag.",
      "Pick a colour and I’ll guess the vibe you bring to dates.",
      "Send your most-used emoji and I’ll make one assumption.",
      "Finish this sentence: the fastest way to impress me is…",
      "Rate your flirting skills from one to professionally dangerous.",
      "Tell me a tiny secret and I’ll trade you one.",
      "Choose your team: sweet, funny, bold, or mysterious?",
      "Drop one opinion and let me guess whether you’re serious.",
      "Three words to describe you on your best day—go.",
      "Name a film and I’ll choose our imaginary first-date snack.",
      "Quick game: what would your friends say is your signature move?",
      "Give me a song title that describes your love life.",
      "Pick one: beach, city, mountains, or my company?",
      "Tell me your comfort meal and I’ll guess your personality.",
      "Complete the sentence: I’m secretly very good at…",
      "Choose a superpower, but it has to help on a date.",
      "Name your current obsession without saying why.",
      "Give me the title of your life’s current episode.",
      "Pick our chat difficulty: easy, bold, or no-filter.",
      "Quick game: ask me something you’d usually wait to ask.",
      "Tell me the last photo in your camera roll using five words.",
      "Choose a date vibe: cosy, classy, chaotic, or outdoorsy.",
      "Rate your spontaneity from calendar invite to ‘I’m outside.’",
      "Name one thing you’d bring to a deserted island besides your phone.",
      "Give me your best bad joke. I promise nothing.",
      "Pick a decade for our imaginary themed party.",
      "Tell me your star sign and let me react irresponsibly.",
      "Choose one message to receive: ‘I miss you’ or ‘I made reservations.’",
      "Name one skill you’d teach me and one you want to learn.",
      "Quick game: what’s your most-used excuse for leaving the house late?",
      "Give me a random fact about you with no context.",
      "Choose your entrance music for our first date.",
      "Tell me your favourite smell and I’ll guess your comfort place.",
      "Pick one personality setting: calm, chaotic, or charmingly both.",
      "Describe your ideal person without mentioning looks.",
      "Name a food you refuse to share. This is a safe space.",
      "Quick game: what’s the nicest assumption you’d make about me?",
      "Give me a nickname based only on my profile.",
      "Choose one: cook together, dress up, or disappear on a day trip.",
      "Tell me the emoji your friends would use to describe you.",
      "Pick a question category: cute, deep, funny, or spicy.",
      "Name something small that gives you instant joy.",
      "Quick game: what’s your most believable fake talent?",
      "Give me your Sunday mood in one GIF description.",
      "Choose a fictional world for our first adventure.",
      "Tell me one thing on your bucket list and I’ll add one.",
      "Pick a number from one to ten—that’s our banter rating goal.",
      "Name your karaoke song and accept the consequences.",
      "Quick game: one compliment each. I’m ready when you are.",
      "Your move: create a tiny game for both of us.",
    ],
  },
  {
    value: "date_energy",
    label: "Date energy",
    seekerOnly: true,
    openers: [
      "Choose our imaginary first date: food, music, or an activity?",
      "What date plan would make you say yes without checking the weather?",
      "Are you more coffee and conversation or dinner and dressed up?",
      "Plan a first date for us using only three words.",
      "What’s your ideal balance between planned and spontaneous on a date?",
      "Would your perfect date start early or end very late?",
      "What’s one date idea you’ve always wanted someone to suggest?",
      "Pick the vibe: rooftop, beach, arcade, or cosy restaurant.",
      "What matters more on a date: the place or the conversation?",
      "Would you rather explore somewhere new or revisit your favourite spot?",
      "What’s your idea of a low-effort but high-quality date?",
      "Do you prefer a first date with an activity or pure conversation?",
      "What food instantly makes a date feel like a good idea?",
      "Would you trust me to plan the whole date?",
      "What would make a simple walk feel romantic to you?",
      "Choose our date soundtrack: Afrobeats, R&B, amapiano, or surprise me.",
      "What’s a date idea that sounds better than another dinner?",
      "Are you dressing casual or giving the outfit a full storyline?",
      "What’s the best first-date question nobody asks?",
      "Would you rather have a picnic or go somewhere with live music?",
      "What’s your perfect after-dinner plan?",
      "Do you prefer dates that feel calm or dates with a little adrenaline?",
      "What local place would you proudly choose for a first date?",
      "Would you rather laugh all night or have one unforgettable deep talk?",
      "What’s your first-date green flag?",
      "How long should a perfect first date last?",
      "Would you pick the restaurant or let me surprise you?",
      "What tiny detail makes a date feel thoughtful?",
      "Choose one: art gallery, food market, game night, or sunset view.",
      "What’s your ideal ‘we lost track of time’ date?",
      "Would you rather do something competitive or something relaxing?",
      "What’s one date idea that sounds romantic but is actually stressful?",
      "Are first dates better in daylight or after dark?",
      "What’s your preferred date dress code: effortless or intentional?",
      "Would you rather talk somewhere quiet or people-watch somewhere busy?",
      "What dessert are we ordering even if we claim we’re full?",
      "Would you rather have the best meal or the best view?",
      "How spontaneous can a date be before it becomes poor planning?",
      "What’s your favourite way for someone to confirm a date?",
      "Would you rather meet for one drink or commit to a full evening?",
      "What makes a date feel safe and easy for you?",
      "Pick our first-date energy: cute, classy, playful, or adventurous.",
      "What would make you want a second date before the first one ends?",
      "Would you rather take photos together or keep phones away?",
      "What’s more romantic: a thoughtful plan or a spontaneous detour?",
      "Choose the starter topic: travel, music, dreams, or harmless gossip.",
      "What date activity reveals someone’s real personality fastest?",
      "Would you rather meet somewhere familiar or somewhere new to both of us?",
      "What’s your definition of being properly courted?",
      "Would you rather split a bottle, split dessert, or share neither?",
      "What’s the earliest sign a date is going really well?",
      "How important is good music to the date atmosphere?",
      "Would you rather arrive separately or get picked up?",
      "What’s your favourite kind of post-date message?",
      "Would you rather have one amazing plan or three surprise stops?",
      "What turns an ordinary outing into a memorable date?",
      "Choose a final stop: dessert, a drive, live music, or one more drink.",
      "What’s your ideal first-date ratio of flirting to real conversation?",
      "Would your perfect date be Instagram-worthy or private and unplanned?",
      "Tell me your date energy and I’ll tell you if I can match it.",
    ],
  },
  {
    value: "straight_up",
    label: "Straight up",
    openers: [
      "I’m interested in you. Are you open to getting to know each other?",
      "No complicated opener—you caught my attention and I wanted to say so.",
      "I like your vibe. I’d genuinely enjoy a conversation with you.",
      "You seem interesting, and I’d rather say hello than wonder.",
      "I’m attracted to you and curious about who you are.",
      "I’d like to get to know you. Simple as that.",
      "Your profile stood out to me. How are you doing?",
      "I think you’re attractive. I’m hoping the conversation is just as good.",
      "I’m not here to waste your time. I’d like to know you better.",
      "You seem like someone worth being direct with: I’m interested.",
      "I saw your profile and decided honesty was the best opener.",
      "I’d enjoy talking with you if the interest is mutual.",
      "You caught my eye, and I wanted to introduce myself properly.",
      "I’m curious about you. Want to have a real conversation?",
      "No games—I think you’re attractive and I’d like to talk.",
      "I like what I see and I’d love to learn what I can’t see yet.",
      "I’m here because you seem genuinely worth meeting.",
      "You have my attention. Can I have a little of yours?",
      "I’d rather be clear: I’d like to explore this connection.",
      "Something about your profile felt worth acting on.",
      "I’m looking for good energy and honest conversation. You seem promising.",
      "I don’t know you yet, but I’d like to change that.",
      "You seem attractive, grounded, and interesting. I had to say hello.",
      "Let me be direct: I’d like to take you out sometime.",
      "I’m interested. What would you want me to know first?",
      "Your profile made a strong first impression. I’d like a second one.",
      "I’m not going to overthink this—you seem great, so hi.",
      "I’d like to know if our energy matches beyond the screen.",
      "I think there could be something worth exploring here.",
      "You’re my kind of attractive, and I’m curious about your mind too.",
      "I’m here with clear intentions and a genuine hello.",
      "You seem like my type of person. Want to find out?",
      "I’m interested enough to be direct and respectful about it.",
      "You stood out. I’d love to know what makes you, you.",
      "I think we should talk and see whether the feeling has somewhere to go.",
      "I’d like to get past profiles and into an actual conversation.",
      "You seem worth the courage it takes to message first.",
      "I’m not looking for a clever line. I’m looking to know you.",
      "I like your energy. Would you be open to a conversation?",
      "This is me making my interest very easy to understand.",
      "I find you attractive and your profile genuinely interesting.",
      "I’d like to see if we have the same kind of chemistry in conversation.",
      "You look like someone I’d enjoy spending time with.",
      "I’m curious enough to say hello and confident enough to mean it.",
      "I want to know more than the highlights on your profile.",
      "You seem intentional. I appreciate that, and I’m interested.",
      "I’d love the chance to get to know you without the usual games.",
      "I’m attracted to your vibe and open to seeing where a chat goes.",
      "You caught my attention for more than just one reason.",
      "I’m looking for someone interesting. Your profile made me pause.",
      "Let’s have a proper conversation and see what happens.",
      "I like your presence. It feels worth reaching out to.",
      "I’m being straightforward because you seem worth it.",
      "You look like someone I could connect with beyond small talk.",
      "I’d rather risk a hello than miss a potentially good person.",
      "I’m genuinely interested in getting to know you better.",
      "You seem like a good person to be intentional about meeting.",
      "I’d like to know whether your conversation matches your energy.",
      "If you’re open to it, I’d enjoy getting to know you.",
      "No pressure, no performance—I just wanted to say I’m interested.",
    ],
  },
  {
    value: "curious",
    label: "Curious",
    openers: [
      "What’s something you could talk about for hours without preparing?",
      "What’s a small thing that instantly improves your mood?",
      "What’s the most interesting thing you’ve learned lately?",
      "Which version of you shows up when you’re completely comfortable?",
      "What’s a dream you don’t talk about often enough?",
      "What’s something people usually get wrong about you?",
      "If your week had a theme song, what would it be?",
      "What’s your favourite way to waste time beautifully?",
      "What’s one opinion you changed your mind about recently?",
      "Which question do you wish people asked you more often?",
      "What makes you lose track of time in the best way?",
      "If tomorrow were completely free, how would you spend it?",
      "What’s the best spontaneous decision you’ve ever made?",
      "What part of your personality took time to grow into?",
      "What are you currently looking forward to most?",
      "What’s a very ordinary thing you’re surprisingly passionate about?",
      "Which memory can always make you smile?",
      "What does a genuinely good day look like for you?",
      "What’s the last thing that made you laugh properly?",
      "If money and fear disappeared, what would you try first?",
      "What’s something you’re proud of that nobody sees?",
      "Who are you when nobody needs anything from you?",
      "What’s one place that changed the way you see things?",
      "What kind of people bring out your best side?",
      "What’s your favourite thing about the life you’re building?",
      "Which compliment has stayed with you the longest?",
      "What’s one thing you want more of this year?",
      "What are you learning about yourself lately?",
      "What’s the most ‘you’ thing about you?",
      "What topic can turn you from quiet to fully animated?",
      "What’s a risk you’re glad you took?",
      "If your closest friend described you, what would they mention first?",
      "What’s one tradition you’d love to create for yourself?",
      "What do you value more now than you did a few years ago?",
      "What’s your current harmless obsession?",
      "Which part of your day feels most peaceful?",
      "What’s something beautiful you noticed recently?",
      "What kind of conversation makes you forget to check your phone?",
      "What’s your favourite story about how you became who you are?",
      "What would your younger self be most impressed by?",
      "What’s a random hill you’ll always defend?",
      "What have you been meaning to do just for yourself?",
      "What’s one thing that always makes you feel at home?",
      "Which quality do you appreciate most in other people?",
      "What’s the best advice you ignored before finally understanding it?",
      "What part of life are you romanticising right now?",
      "What’s your favourite way to show someone you care?",
      "What do you wish you had more time to explore?",
      "What’s a side of you your profile doesn’t show yet?",
      "Which experience taught you more than you expected?",
      "What’s the nicest thing you’ve done for yourself lately?",
      "What are you very curious about at the moment?",
      "What would make this month feel like a win?",
      "What’s something you believe that experience taught you?",
      "Where does your mind go when you need a little escape?",
      "What’s your idea of chemistry that goes beyond attraction?",
      "What’s a question you’re still figuring out the answer to?",
      "Which part of your life feels most exciting right now?",
      "What makes a conversation memorable for you?",
      "Tell me one thing about you that deserves a follow-up question.",
    ],
  },
  {
    value: "playful",
    label: "Playful",
    openers: [
      "I’ll guess your vibe in three questions. Ready?",
      "Pick one: spontaneous road trip, rooftop drinks, or cosy night in?",
      "You get one song to control the aux. What are you playing?",
      "Let’s skip ‘how are you’—what kind of trouble are we choosing?",
      "I’ll trade you one fun fact for one mildly embarrassing story.",
      "Choose our first debate: food, music, or who texts first?",
      "Your profile says fun. I’m here to verify the claim.",
      "Give me two truths and a lie, but make the lie convincing.",
      "You seem competitive. What game are you absolutely beating me at?",
      "Let’s make this easy: ask me the question you actually want answered.",
      "Pick a number from one to ten and I’ll assign us an adventure.",
      "What nickname would your friends warn me about?",
      "I have a theory about your personality. Want to hear it?",
      "We can do small talk, or you can tell me your wildest harmless idea.",
      "I’m giving you control of the first topic. Use the power wisely.",
      "Would you rather plan the date or choose the surprise?",
      "Tell me your comfort food and I’ll make one bold assumption.",
      "Let’s see if we’re compatible: early arrival or dramatic entrance?",
      "What’s your most chaotic green flag?",
      "I’ll start: my first impression of you is dangerously fun.",
      "You look like you’d turn a simple errand into a full adventure.",
      "What would our duo name be if we became a minor inconvenience?",
      "Pick your fighter: witty banter, deep talks, or shameless flirting.",
      "I’m challenging you to make me laugh in one message.",
      "What’s the most unserious reason you’ve ever liked someone?",
      "I’ll let you choose: honest question or playful dare?",
      "Your move—tell me something that’ll make replying irresistible.",
      "If our vibe were a film genre, what are you guessing?",
      "What’s one thing you’d definitely tease me about?",
      "You seem like a person with an elite reaction GIF collection.",
      "Let’s pretend we already know each other. What are we arguing about?",
      "I’m rating first impressions today. Want your score?",
      "What’s your signature move when you’re trying to charm someone?",
      "I’ll bring the questions if you bring the unpredictable answers.",
      "Which version of fun are you: planned chaos or accidental chaos?",
      "You get to steal one thing from my profile. What is it?",
      "What’s our first inside joke going to be about?",
      "Convince me you’re as fun as your profile in five words.",
      "I’m curious: sweet first, sarcastic later, or the reverse?",
      "Choose a vibe for this chat: cute, chaotic, or suspiciously honest.",
      "You look like you’d make a bet and refuse to lose.",
      "What’s the fastest way to get you out of the house?",
      "Let’s exchange one red flag and one redeeming quality.",
      "I’ve decided you’re interesting. Appeals are open.",
      "What’s the most spontaneous plan you’d say yes to tonight?",
      "Your profile gives me questions. Mostly fun ones.",
      "If I guessed your favourite snack correctly, what do I win?",
      "Let’s play: describe your personality using only three emojis.",
      "You seem like someone who can handle premium banter.",
      "I’ll go first: you look like a good decision with bad timing.",
      "Pick one secret talent to reveal. I promise appropriate applause.",
      "What’s your ‘this always works on me’ move?",
      "We have one hour and no plan. Where are we ending up?",
      "Are you the planner, the passenger, or the person changing the plan?",
      "Tell me a harmless lie about yourself and let me guess.",
      "I’m offering you one chance to impress me with a random opinion.",
      "Would your friends call you the calm one or the reason plans escalate?",
      "You look like you know how to make a boring day interesting.",
      "What’s your opening move when you know the vibe is mutual?",
      "I brought curiosity and good banter. What did you bring?",
    ],
  },
  {
    value: "spicy",
    label: "Spicy",
    openers: [
      "That look in your eyes deserves a conversation with better lighting.",
      "You have the kind of energy that makes innocent thoughts resign.",
      "I’m trying to be respectful, but you’re making mysterious very attractive.",
      "Your profile just turned my imagination into an active participant.",
      "You look like a slow conversation that gets dangerously interesting.",
      "I have a feeling your voice would make this crush significantly worse.",
      "You’re giving ‘come closer’ energy from very far away.",
      "The tension is imaginary so far, but it has excellent potential.",
      "You look like you know exactly what that smile does.",
      "I’d like to hear the thoughts you don’t put on your profile.",
      "Your vibe is somewhere between temptation and a very good idea.",
      "I’m curious how much trouble fits behind that calm expression.",
      "There’s something about you that makes subtlety feel unrealistic.",
      "You look like the reason somebody forgets what they were saying.",
      "I’m keeping this message polite. My thoughts are negotiating.",
      "You have the kind of confidence that makes eye contact feel personal.",
      "I can already tell our chemistry wouldn’t be quiet.",
      "Your smile looks like it knows how to start something.",
      "I’m wondering whether you’re as bold as your energy suggests.",
      "You look like a very good reason to stay up too late.",
      "I feel like you’d be even more distracting across a table.",
      "That profile has no business creating this many thoughts.",
      "You seem like someone who knows when to whisper the interesting part.",
      "I’m interested in the version of you that comes out after midnight.",
      "Your energy says innocent smile, questionable intentions.",
      "I would absolutely lose my train of thought around you.",
      "You look like you could make ‘come over’ sound very convincing.",
      "The attraction is obvious. I’m curious about the tension.",
      "I’m trying to decide whether your eyes or your smile are more dangerous.",
      "You’re giving me thoughts that require a better conversation.",
      "I have a feeling you’re very good at making people lean closer.",
      "Your profile feels like the beginning of a deliciously bad decision.",
      "You look like the kind of person who enjoys a little anticipation.",
      "I’m not rushing anything, but I am enjoying the direction of my thoughts.",
      "Something tells me your flirting comes with excellent eye contact.",
      "You seem like you’d make silence feel anything but awkward.",
      "That confidence is doing things your photos didn’t even ask it to do.",
      "You have a very convincing ‘stay a little longer’ vibe.",
      "I’d like to discover which part of your personality is most addictive.",
      "You look like a conversation that starts sweet and loses its innocence.",
      "I’m curious what kind of compliment makes you bite your lip.",
      "The way you carry yourself is quietly doing a lot.",
      "You seem like someone who appreciates tension before the plot develops.",
      "I was going to play it safe, then I looked at your profile again.",
      "You have the kind of presence that makes personal space negotiable.",
      "I’m interested in your mind. The rest of you is not exactly hurting.",
      "You look like you’d turn a normal goodnight into a difficult decision.",
      "I’d like to know what that smile looks like when it’s meant for me.",
      "Your energy feels warm, confident, and slightly dangerous.",
      "I can be patient, but your profile is testing the philosophy.",
      "You seem like the kind of distraction people willingly choose.",
      "I have a respectful amount of very disrespectful curiosity.",
      "You look like chemistry with a warning label.",
      "I’m wondering how quickly this conversation could stop being innocent.",
      "Your vibe says you know exactly how to build suspense.",
      "I’d ask what you’re thinking, but I’m hoping it’s slightly inappropriate.",
      "You have ‘one more minute’ energy, and I know how that story ends.",
      "I’m behaving for now. Consider this your head start.",
      "You look like the reason self-control needs regular practice.",
      "Let’s start with conversation and see how long we stay well behaved.",
    ],
  },
  {
    value: "confident",
    label: "Confident",
    openers: [
      "You caught my attention. I’m here to return the favour.",
      "I like your energy. Let’s see if you can match mine.",
      "I don’t usually hesitate, and your profile made the decision easy.",
      "You look interesting. I’m giving us a chance to prove it.",
      "I know good energy when I see it, so hello.",
      "I’m here because I think we’d have a very good conversation.",
      "You stood out. I trust my taste.",
      "I’m confident we’d get along. Feel free to challenge the theory.",
      "You look like someone worth making the first move for.",
      "I like what your profile is giving. Tell me what it missed.",
      "I’m not waiting for fate to do all the work.",
      "You have my attention, and I don’t give it carelessly.",
      "I think we’d make a strong first impression together.",
      "You seem like quality. I prefer introducing myself to guessing.",
      "I saw the vibe, respected it, and came to say hello.",
      "Let’s skip uncertainty—I’m interested.",
      "I have good instincts. They told me to message you.",
      "You look like someone who appreciates direct energy.",
      "I’m making the first move. You can make the second one count.",
      "You seem worth a proper introduction, so here I am.",
      "I don’t need a pickup line to know I want to talk to you.",
      "I like confidence, and something tells me you do too.",
      "Your profile passed my very unofficial quality check.",
      "I think your attention would look good over here.",
      "You’re attractive. I’m intentional. Let’s start there.",
      "I came to find out whether your conversation is as strong as your presence.",
      "I’m not competing for your attention. I’m offering better conversation.",
      "You seem like someone I’d enjoy being boldly myself around.",
      "I know what I like, and your profile made the list.",
      "I’d rather introduce myself than silently admire from a distance.",
      "You look like someone who can handle honesty: I’m interested.",
      "Let’s find out if the vibe is as mutual as it looks.",
      "I’m not here by accident. You genuinely caught my eye.",
      "I think we’d be memorable together. Conversation first.",
      "You have presence. I respect that and wanted to meet it directly.",
      "I’m choosing confidence over another pointless scroll.",
      "You seem like someone who values people who know what they want.",
      "I want to know you, so I’m starting the conversation.",
      "I’m bringing clear interest and good energy. Your move.",
      "You look like a person who deserves more than a shy hello.",
      "I see potential here, and I’m comfortable saying it.",
      "I’m not overthinking this. Attractive person, genuine interest, hello.",
      "I have a feeling you’re worth being brave for.",
      "Your profile caught my attention; your reply can keep it.",
      "I’m here with intention, curiosity, and excellent timing.",
      "You look like someone I could admire and still banter with.",
      "I trust myself enough to act when someone stands out.",
      "I think you’re interesting. Let’s not leave that untested.",
      "You have the kind of energy I’d make room for.",
      "I’m looking for a real spark, and your profile has potential.",
      "I came to say hello before the moment became a missed opportunity.",
      "You seem like someone who can meet directness with directness.",
      "I’m interested in your story, not just your highlights.",
      "You look like a conversation I’d be glad I started.",
      "Let’s make this simple: I like your vibe.",
      "I’m confident enough to say you’re exactly worth messaging.",
      "You caught my eye. Now tell me something worth remembering.",
      "I like the way you show up. I’d like to know more.",
      "I’m making an executive decision: we should talk.",
      "Consider this a confident hello with genuinely good intentions.",
    ],
  },
];

export function isMessageOpenerCategoryId(value: unknown): value is MessageOpenerCategoryId {
  return typeof value === "string" && MESSAGE_OPENER_CATEGORY_IDS.includes(value as MessageOpenerCategoryId);
}

export function getMessageOpenerCategoriesForProfile(
  profileType: "EXPLORER" | "SEEKER" | "CREATOR",
): readonly MessageOpenerCategory[] {
  if (profileType === "SEEKER") {
    return SEEKER_OPENER_ORDER.map((id) => MESSAGE_OPENER_CATEGORIES.find((category) => category.value === id)).filter(
      (category): category is MessageOpenerCategory => Boolean(category),
    );
  }
  return MESSAGE_OPENER_CATEGORIES.filter((category) => !category.seekerOnly);
}

/** Builds a fresh shuffle bag and keeps the first draw from repeating the line just shown. */
export function shuffleMessageOpeners(
  openers: readonly string[],
  previous?: string,
  random: () => number = Math.random,
): string[] {
  const deck = [...openers];
  for (let index = deck.length - 1; index > 0; index -= 1) {
    const other = Math.floor(random() * (index + 1));
    [deck[index], deck[other]] = [deck[other], deck[index]];
  }

  if (previous && deck.length > 1 && deck[deck.length - 1] === previous) {
    [deck[0], deck[deck.length - 1]] = [deck[deck.length - 1], deck[0]];
  }
  return deck;
}
